[project]
name = "00-uv-simple-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []


[project.scripts]
myapp = "main:main"

[tool.uv]
package = true